# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.IntegerField(default=None),
        ),
    ]
